In [44]:
import pandas                   # Leer el archivo csv
import numpy as np              # Operaciones con vectores y matrices
import matplotlib.pyplot as plt # Gr√°ficas

In [45]:
df = pandas.read_csv('adult.csv',sep=",")
df

,age,workclass,education,education-num,marital-status,occupation,relationship,race,sex,hours-per-week,native-country,income
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,40,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,13,United-States,<=50K
2,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,40,United-States,<=50K
3,53,Private,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,40,United-States,<=50K
4,28,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,40,Cuba,<=50K
5,37,Private,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,40,United-States,<=50K
6,49,Private,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,16,Jamaica,<=50K
7,52,Self-emp-not-inc,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,45,United-States,>50K
8,31,Private,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,50,United-States,>50K
9,42,Private,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,40,United-States,>50K
10,37,Private,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,80,United-States,>50K
11,30,State-gov,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,40,India,>50K
12,23,Private,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,30,United-States,<=50K
13,32,Private,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,50,United-States,<=50K
14,40,Private,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,40,?,>50K
15,34,Private,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,45,Mexico,<=50K
16,25,Self-emp-not-inc,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,35,United-States,<=50K
17,32,Private,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,40,United-States,<=50K
18,38,Private,11th,7,Married-civ-spouse,Sales,Husband,White,Male,50,United-States,<=50K
19,43,Self-emp-not-inc,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,45,United-States,>50K
20,40,Private,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,60,United-States,>50K
21,54,Private,HS-grad,9,Separated,Other-service,Unmarried,Black,Female,20,United-States,<=50K
22,35,Federal-gov,9th,5,Married-civ-spouse,Farming-fishing,Husband,Black,Male,40,United-States,<=50K
23,43,Private,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,40,United-States,<=50K
24,59,Private,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,40,United-States,<=50K
25,56,Local-gov,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,40,United-States,>50K
26,19,Private,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,40,United-States,<=50K
27,54,?,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,60,South,>50K
28,39,Private,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,80,United-States,<=50K
29,49,Private,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...
32531,30,?,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Female,99,United-States,<=50K
32532,34,Private,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,60,United-States,>50K
32533,54,Private,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,50,Japan,>50K
32534,37,Private,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,39,United-States,<=50K
32535,22,Private,12th,8,Never-married,Protective-serv,Own-child,Black,Male,35,United-States,<=50K
32536,34,Private,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,55,United-States,>50K
32537,30,Private,HS-grad,9,Never-married,Craft-repair,Not-in-family,Black,Male,46,United-States,<=50K
32538,38,Private,Bachelors,13,Divorced,Prof-specialty,Unmarried,Black,Female,45,United-States,>50K
32539,71,?,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,10,United-States,>50K
32540,45,State-gov,HS-grad,9,Separated,Adm-clerical,Own-child,White,Female,40,United-States,<=50K
32541,41,?,HS-grad,9,Separated,?,Not-in-family,Black,Female,32,United-States,<=50K
32542,72,?,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,25,United-States,<=50K
32543,45,Local-gov,Assoc-acdm,12,Divorced,Prof-specialty,Unmarried,White,Female,48,United-States,<=50K
32544,31,Private,Masters,14,Divorced,Other-service,Not-in-family,Other,Female,30,United-States,<=50K
32545,39,Local-gov,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,20,United-States,>50K
32546,37,Private,Assoc-acdm,12,Divorced,Tech-support,Not-in-family,White,Female,40,United-States,<=50K
32547,43,Private,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,40,Mexico,<=50K
32548,65,Self-emp-not-inc,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,60,United-States,<=50K
32549,43,State-gov,Some-college,10,Divorced,Adm-clerical,Other-relative,White,Female,40,United-States,<=50K
32550,43,Self-emp-not-inc,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,50,United-States,<=50K
32551,32,Private,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,40,United-States,<=50K
32552,43,Private,Assoc-voc,11,Married-civ-spouse,Sales,Husband,White,Male,45,United-States,<=50K
32553,32,Private,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,11,Taiwan,<=50K
32554,53,Private,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,40,United-States,>50K
32555,22,Private,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,40,United-States,<=50K
32556,27,Private,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,38,United-States,<=50K
32557,40,Private,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,40,United-States,>50K
32558,58,Private,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,40,United-States,<=50K
32559,22,Private,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,20,United-States,<=50K
32560,52,Self-emp-inc,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,40,United-States,>50K

In [46]:
var = 2
name = df.columns[var]
values = df.values[:,var]
print(name)
print(values)

education
[' Bachelors' ' Bachelors' ' HS-grad' ... ' HS-grad' ' HS-grad' ' HS-grad']

In [47]:
# Frecuencias
vunique, vcounts = np.unique( values, return_counts=True )
print(vunique)
print(vcounts)

[' 10th' ' 11th' ' 12th' ' 1st-4th' ' 5th-6th' ' 7th-8th' ' 9th'
 ' Assoc-acdm' ' Assoc-voc' ' Bachelors' ' Doctorate' ' HS-grad'
 ' Masters' ' Preschool' ' Prof-school' ' Some-college']
[  933  1175   433   168   333   646   514  1067  1382  5355   413 10501
  1723    51   576  7291]

In [48]:
# Entropy
def entropy(X):
    # H = - Sum ( P(x) log( P(x)))
    h = 0
    n = len(X)
    vunique, vcounts = np.unique( X, return_counts=True )
    for u, c in zip( vunique, vcounts):
        prob = c / n
        h += prob * np.log2(prob)
    return -h , - np.log2( 1/len(vunique) )

h = entropy(values)
print(h)

(2.931350897803711, 4.0)

In [49]:
for var in range(len(df.columns)):
    name = df.columns[var]
    values = df.values[:,var]
    h, hM = entropy(values)
    print(name,h,hM)

age 5.683324396400327 6.189824558880018
workclass 1.647976927509927 3.1699250014423126
education 2.931350897803711 4.0
education-num 2.9313508978037106 4.0
marital-status 1.8336493538835446 2.807354922057604
occupation 3.516903064343104 3.9068905956085187
relationship 2.1544237955049743 2.584962500721156
race 0.7987406510139586 2.321928094887362
sex 0.9157360598501509 1.0
hours-per-week 3.4795648800680166 6.554588851677638
native-country 0.9437954138017219 5.392317422778761
income 0.7963839552022132 1.0

In [52]:
def mutual_information(X, Y):
    x_ = df.columns[X] # Header
    y_ = df.columns[Y] # Header
    
    uniqueX = np.unique(df.values[:,X], return_counts = False) # Types
    uniqueY = np.unique(df.values[:,Y], return_counts = False) # Types
    
    total = len(df.values[:,X]) # number of rows
    
    n = len(uniqueX) # number of distinct types
    m = len(uniqueY)    

    Px, Py = 0,0
    Pxy = 0
    mi = 0
    for i in range(0,n):
        Px = len(df[df[x_]==uniqueX[i]])/total
        #print(Px)
        for j in range(0,m):
            Py = len(df[df[y_]==uniqueY[j]])/total
            
            cant = len(df[(df[x_]==uniqueX[i]) & (df[y_]==uniqueY[j])]) # Intersection between x and y
            Pxy = cant/total
            #print(Pxy)
            if (Pxy/(Px*Py)<=0):
                mi += 0
            else:
                mi += (Pxy * np.log2(Pxy /(Px*Py)))
    
    return mi

for var1 in range(len(df.columns)):
    for var2 in range(var1+1,len(df.columns)):

        name1 = df.columns[var1]
        values1 = df.values[:,var1]
        h1, hM1 = entropy(values1)
        
        name2 = df.columns[var2]
        values2 = df.values[:,var2]
        h2, hM2 = entropy(values2)

        
        im = mutual_information(var1,var2)
        
        print(name1,h1,name2,h2,im)

age 5.683324396400327 workclass 1.647976927509927 0.08962060950941193
age 5.683324396400327 education 2.931350897803711 0.1664031215108037
age 5.683324396400327 education-num 2.9313508978037106 0.16640312151080372
age 5.683324396400327 marital-status 1.8336493538835446 0.3554098240073331
age 5.683324396400327 occupation 3.516903064343104 0.1256778570661102
age 5.683324396400327 relationship 2.1544237955049743 0.2890653412789402
age 5.683324396400327 race 0.7987406510139586 0.009931398092599582
age 5.683324396400327 sex 0.9157360598501509 0.012833119587376773
age 5.683324396400327 hours-per-week 3.4795648800680166 0.25028922675198395
age 5.683324396400327 native-country 0.9437954138017219 0.05733177885706737
age 5.683324396400327 income 0.7963839552022132 0.09921780194414098
workclass 1.647976927509927 education 2.931350897803711 0.047140888816564405
workclass 1.647976927509927 education-num 2.9313508978037106 0.0471408888165644
workclass 1.647976927509927 marital-status 1.8336493538835446 0.031334022640241536
workclass 1.647976927509927 occupation 3.516903064343104 0.4712021200446486
workclass 1.647976927509927 relationship 2.1544237955049743 0.03528426599704064
workclass 1.647976927509927 race 0.7987406510139586 0.010107476012667576
workclass 1.647976927509927 sex 0.9157360598501509 0.018833173794477177
workclass 1.647976927509927 hours-per-week 3.4795648800680166 0.08911335550201603
workclass 1.647976927509927 native-country 0.9437954138017219 0.013488055620187416
workclass 1.647976927509927 income 0.7963839552022132 0.02157159019812267
education 2.931350897803711 education-num 2.9313508978037106 2.931350897803711
education 2.931350897803711 marital-status 1.8336493538835446 0.03450682250802299
education 2.931350897803711 occupation 3.516903064343104 0.3226772938074207
education 2.931350897803711 relationship 2.1544237955049743 0.05435326972057027
education 2.931350897803711 race 0.7987406510139586 0.01490447578010681
education 2.931350897803711 sex 0.9157360598501509 0.006851814658325971
education 2.931350897803711 hours-per-week 3.4795648800680166 0.08436809790676825
education 2.931350897803711 native-country 0.9437954138017219 0.07793357504954693
education 2.931350897803711 income 0.7963839552022132 0.09359084108861465
education-num 2.9313508978037106 marital-status 1.8336493538835446 0.034506822508023005
education-num 2.9313508978037106 occupation 3.516903064343104 0.3226772938074206
education-num 2.9313508978037106 relationship 2.1544237955049743 0.05435326972057029
education-num 2.9313508978037106 race 0.7987406510139586 0.014904475780106802
education-num 2.9313508978037106 sex 0.9157360598501509 0.006851814658325973
education-num 2.9313508978037106 hours-per-week 3.4795648800680166 0.08436809790676827
education-num 2.9313508978037106 native-country 0.9437954138017219 0.07793357504954694
education-num 2.9313508978037106 income 0.7963839552022132 0.09359084108861462
marital-status 1.8336493538835446 occupation 3.516903064343104 0.07762299555762298
marital-status 1.8336493538835446 relationship 2.1544237955049743 1.046677309245545
marital-status 1.8336493538835446 race 0.7987406510139586 0.01854709249186529
marital-status 1.8336493538835446 sex 0.9157360598501509 0.1634191261430612
marital-status 1.8336493538835446 hours-per-week 3.4795648800680166 0.0779283413113054
marital-status 1.8336493538835446 native-country 0.9437954138017219 0.017175001947161143
marital-status 1.8336493538835446 income 0.7963839552022132 0.15652786512566177
occupation 3.516903064343104 relationship 2.1544237955049743 0.12135936053737291
occupation 3.516903064343104 race 0.7987406510139586 0.018315015613729335
occupation 3.516903064343104 sex 0.9157360598501509 0.14327254755802382
occupation 3.516903064343104 hours-per-week 3.4795648800680166 0.17961662215356755
occupation 3.516903064343104 native-country 0.9437954138017219 0.04209336092996876
occupation 3.516903064343104 income 0.7963839552022132 0.09292248395497077
relationship 2.1544237955049743 race 0.7987406510139586 0.024373178029066474
relationship 2.1544237955049743 sex 0.9157360598501509 0.39406792392795054
relationship 2.1544237955049743 hours-per-week 3.4795648800680166 0.11232527480975577
relationship 2.1544237955049743 native-country 0.9437954138017219 0.018312100332194124
relationship 2.1544237955049743 income 0.7963839552022132 0.16536575798521508
race 0.7987406510139586 sex 0.9157360598501509 0.009554553757167607
race 0.7987406510139586 hours-per-week 3.4795648800680166 0.02048905085674826
race 0.7987406510139586 native-country 0.9437954138017219 0.14146309965665443
race 0.7987406510139586 income 0.7963839552022132 0.008377946328510508
sex 0.9157360598501509 hours-per-week 3.4795648800680166 0.05767563165956453
sex 0.9157360598501509 native-country 0.9437954138017219 0.003350698967973215
sex 0.9157360598501509 income 0.7963839552022132 0.03717138743832124
hours-per-week 3.4795648800680166 native-country 0.9437954138017219 0.043541924263480906
hours-per-week 3.4795648800680166 income 0.7963839552022132 0.06100193925347576
native-country 0.9437954138017219 income 0.7963839552022132 0.008695342020861101